language: java
sudo: false
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true -B -V
script: mvn test -Dmaven.javadoc.skip=true -Dgpg.skip=true -B -V
jdk:
  - oraclejdk8

after_success:
  - bash <(curl -s https://codecov.io/bash)
